DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
DROP TABLE IF EXISTS uploads;
CREATE TABLE uploads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file_name varchar(150) NOT NULL,
  upload_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE services (
    id INTEGER PRIMARY KEY AUTOINCREMENT ,
    author_id INTEGER,
    created TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    name varchar,
    description TEXT,
    url_dir VARCHAR

);